In [1]:
import pandas as pd
import seaborn as sns

In [2]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\saksh\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\saksh\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\saksh\anaconda3\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\saksh\anaconda3\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saksh\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saksh\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saksh\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\saksh\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import math

In [4]:
list=[1,2,3,4,5,6,7,8]
list[:4]

[1, 2, 3, 4]

In [5]:
list[0:]

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
import pandas as pd

In [7]:
list_1=[1,2,3,4]
series=pd.Series(list_1)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
index=pd.Series([1,2,3,4,5,6], index=["a","b","c","d","e","f"])
index[:"f"]

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [9]:
list1 = [2,4,6,8]
list2 = []
for i in list1:
    list2.append(i +2)
print(list2)

[4, 6, 8, 10]

In [10]:
list1 = [2,4,6,8]
list2 = []
for i in list1:
    list2.append(i*4)
print(list2)

[8, 16, 24, 32]

##Vectorized operation

In [12]:
import pandas as pd

In [13]:
series=pd.Series([1,2,3,4])

In [14]:
series+2

0    3
1    4
2    5
3    6
dtype: int64

In [15]:
series*2

0    2
1    4
2    6
3    8
dtype: int64

In [16]:
series1=series+2

In [17]:
series1

0    3
1    4
2    5
3    6
dtype: int64

In [18]:
series*8

0     8
1    16
2    24
3    32
dtype: int64

In [19]:
def fun(x):
    return x**2
eg=fun(2)
eg

4

In [20]:
eg1=lambda x:x**2
eg1(4)

16

In [21]:
print(series.apply(lambda x:x/2))

0    0.5
1    1.0
2    1.5
3    2.0
dtype: float64

In [22]:
series_na=pd.Series([5,10,15,None,25])
print(series_na)

0     5.0
1    10.0
2    15.0
3     NaN
4    25.0
dtype: float64

In [23]:
series_na=pd.Series([5,10,15,None,25])
series_na.isna()

0    False
1    False
2    False
3     True
4    False
dtype: bool

To add new value on place of null values after findout in series

In [24]:

series_na.fillna(1,inplace=True)
series_na

0     5.0
1    10.0
2    15.0
3     1.0
4    25.0
dtype: float64

# Data Frames

In [26]:
df=pd.DataFrame({'country':['India','usa','uk'],'state':
                ['bihar','chicago','britain'],'capital':['New delhi','washington','london']})
print (df)

  country    state     capital
0   India    bihar   New delhi
1     usa  chicago  washington
2      uk  britain      london

In [27]:
df1=sns.get_dataset_names()
df1

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [28]:
print(df1)

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [29]:
df1=sns.load_dataset("iris")
df1

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'friends.csv', 'friends_index_false.csv', 'train.csv', 'Untitled.ipynb', 'untitled.txt', 'Untitled1.ipynb', 'Untitled2.ipynb']

In [37]:
df_csv=pd.read_csv("S:/covid_19_clean_complete 1.csv")

In [39]:
df_csv

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [43]:
df_xlsx=pd.read_excel("S:/Superstore.xlsx")

In [45]:
df_xlsx

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,NaN,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,NaN,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,NaN,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [47]:
df_csv.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [49]:
df_csv.head(12)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa
5,NaN,Antigua and Barbuda,17.06080,-61.796400,2020-01-22,0,0,0,0,Americas
6,NaN,Argentina,-38.41610,-63.616700,2020-01-22,0,0,0,0,Americas
7,NaN,Armenia,40.06910,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.47350,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.86880,151.209300,2020-01-22,0,0,0,0,Western Pacific
10,Northern Territory,Australia,-12.46340,130.845600,2020-01-22,0,0,0,0,Western Pacific
11,Queensland,Australia,-27.46980,153.025100,2020-01-22,0,0,0,0,Western Pacific

In [51]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [53]:
df_csv.describe()

,Lat,Long,Confirmed,Deaths,Recovered,Active
count,49068.000000,49068.000000,4.906800e+04,49068.000000,4.906800e+04,4.906800e+04
mean,21.433730,23.528236,1.688490e+04,884.179160,7.915713e+03,8.085012e+03
std,24.950320,70.442740,1.273002e+05,6313.584411,5.480092e+04,7.625890e+04
min,-51.796300,-135.000000,0.000000e+00,0.000000,0.000000e+00,-1.400000e+01
25%,7.873054,-15.310100,4.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,23.634500,21.745300,1.680000e+02,2.000000,2.900000e+01,2.600000e+01
75%,41.204380,80.771797,1.518250e+03,30.000000,6.660000e+02,6.060000e+02
max,71.706900,178.065000,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06

In [55]:
# selecting data
print(df_csv['Confirmed'].head(25))
print('\nDisplaying 5 rows of select column')

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
Name: Confirmed, dtype: int64

Displaying 5 rows of select column

In [57]:
df_csv.Lat.head(10)

0    33.93911
1    41.15330
2    28.03390
3    42.50630
4   -11.20270
5    17.06080
6   -38.41610
7    40.06910
8   -35.47350
9   -33.86880
Name: Lat, dtype: float64

In [59]:
df_csv[['Date','Recovered','Active']].head(15)

          Date  Recovered  Active
0   2020-01-22          0       0
1   2020-01-22          0       0
2   2020-01-22          0       0
3   2020-01-22          0       0
4   2020-01-22          0       0
5   2020-01-22          0       0
6   2020-01-22          0       0
7   2020-01-22          0       0
8   2020-01-22          0       0
9   2020-01-22          0       0
10  2020-01-22          0       0
11  2020-01-22          0       0
12  2020-01-22          0       0
13  2020-01-22          0       0
14  2020-01-22          0       0

In [63]:
df_csv[['Date','Recovered','Active']].tail(15)

             Date  Recovered  Active
49053  2020-07-27          7       0
49054  2020-07-27         36      61
49055  2020-07-27         63     674
49056  2020-07-27        301      76
49057  2020-07-27       1317     400
49058  2020-07-27       1645    1920
49059  2020-07-27         13       0
49060  2020-07-27          1       3
49061  2020-07-27       1175    1084
49062  2020-07-27          8       1
49063  2020-07-27        734     117
49064  2020-07-27        833     375
49065  2020-07-27        328      19
49066  2020-07-27       6028    1147
49067  2020-07-27        128     365

In [65]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [67]:
df_csv.iloc[49]

Province/State            Beijing
Country/Region              China
Lat                       40.1824
Long                     116.4142
Date                   2020-01-22
Confirmed                      14
Deaths                          0
Recovered                       0
Active                         14
WHO Region        Western Pacific
Name: 49, dtype: object

In [69]:
print(df_csv.iloc[50:55])

   Province/State Country/Region      Lat      Long        Date  Confirmed  \
50      Chongqing          China  30.0572  107.8740  2020-01-22          6
51         Fujian          China  26.0789  117.9874  2020-01-22          1
52          Gansu          China  35.7518  104.2861  2020-01-22          0
53      Guangdong          China  23.3417  113.4244  2020-01-22         26
54        Guangxi          China  23.8298  108.7881  2020-01-22          2

    Deaths  Recovered  Active       WHO Region
50       0          0       6  Western Pacific
51       0          0       1  Western Pacific
52       0          0       0  Western Pacific
53       0          0      26  Western Pacific
54       0          0       2  Western Pacific

In [73]:
filter_df = df_csv[df_csv["Confirmed"]>168]

In [75]:
filter_df

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
61,Hubei,China,30.975600,112.270700,2020-01-22,444,17,28,399,Western Pacific
322,Hubei,China,30.975600,112.270700,2020-01-23,444,17,28,399,Western Pacific
583,Hubei,China,30.975600,112.270700,2020-01-24,549,24,31,494,Western Pacific
844,Hubei,China,30.975600,112.270700,2020-01-25,761,40,32,689,Western Pacific
1105,Hubei,China,30.975600,112.270700,2020-01-26,1058,52,42,964,Western Pacific
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [77]:
filter_df.describe()

,Lat,Long,Confirmed,Deaths,Recovered,Active
count,24457.000000,24457.000000,2.445700e+04,24457.000000,2.445700e+04,2.445700e+04
mean,24.691262,32.080544,3.384804e+04,1773.182484,1.586650e+04,1.620836e+04
std,24.672276,66.273819,1.787167e+05,8854.352426,7.680673e+04,1.074064e+05
min,-42.882100,-127.647600,1.690000e+02,0.000000,0.000000e+00,-1.400000e+01
25%,9.748900,-1.561600,5.760000e+02,7.000000,1.650000e+02,1.360000e+02
50%,30.057200,25.485800,1.528000e+03,31.000000,6.720000e+02,6.120000e+02
75%,42.708678,100.992541,1.028700e+04,244.000000,3.236000e+03,4.252000e+03
max,64.963100,174.886000,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06

In [81]:
df_csv['State'] = df_csv['Province/State']

In [83]:
df_csv

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,State
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean,NaN
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe,NaN
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa,NaN
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe,NaN
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa,NaN
...,...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa,NaN
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean,NaN
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa,NaN
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe,NaN
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa,NaN

In [85]:
df_csv1 = df_csv[df_csv['Country/Region'] == 'india'].head(5)
df_csv1

Empty DataFrame
Columns: [Province/State, Country/Region, Lat, Long, Date, Confirmed, Deaths, Recovered, Active, WHO Region, State]
Index: []

In [87]:
df_csv1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  0 non-null      object
 1   Country/Region  0 non-null      object
 2   Lat             0 non-null      float64
 3   Long            0 non-null      float64
 4   Date            0 non-null      object
 5   Confirmed       0 non-null      int64
 6   Deaths          0 non-null      int64
 7   Recovered       0 non-null      int64
 8   Active          0 non-null      int64
 9   WHO Region      0 non-null      object
 10  State           0 non-null      object
dtypes: float64(2), int64(4), object(5)
memory usage: 0.0+ bytes

In [89]:
df_csv1['City'] = ['Hyderabad','Mumbai','Chennai','Bangalore','Tirupati']
df_csv1

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,State,City
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tirupati

In [91]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
 10  State           14664 non-null  object
dtypes: float64(2), int64(4), object(5)
memory usage: 4.1+ MB

In [93]:
filtered_df=df_csv[df_csv['Deaths']>200]

In [95]:
filtered_df

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,State
2410,Hubei,China,30.975600,112.270700,2020-01-31,5806,204,141,5461,Western Pacific,Hubei
2671,Hubei,China,30.975600,112.270700,2020-02-01,7153,249,168,6736,Western Pacific,Hubei
2932,Hubei,China,30.975600,112.270700,2020-02-02,11177,350,295,10532,Western Pacific,Hubei
3193,Hubei,China,30.975600,112.270700,2020-02-03,13522,414,386,12722,Western Pacific,Hubei
3454,Hubei,China,30.975600,112.270700,2020-02-04,16678,479,522,15677,Western Pacific,Hubei
...,...,...,...,...,...,...,...,...,...,...,...
49020,NaN,Ukraine,48.379400,31.165600,2020-07-27,67096,1636,37202,28258,Europe,NaN
49021,NaN,United Arab Emirates,23.424076,53.847818,2020-07-27,59177,345,52510,6322,Eastern Mediterranean,NaN
49028,NaN,United Kingdom,55.378100,-3.436000,2020-07-27,300111,45759,0,254352,Europe,NaN
49030,NaN,US,40.000000,-100.000000,2020-07-27,4290259,148011,1325804,2816444,Americas,NaN
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean,NaN

In [97]:
specific_df=df_csv[df_csv['Country/Region']=='US']

In [99]:
specific_df

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,State
223,NaN,US,40.0,-100.0,2020-01-22,1,0,0,1,Americas,NaN
484,NaN,US,40.0,-100.0,2020-01-23,1,0,0,1,Americas,NaN
745,NaN,US,40.0,-100.0,2020-01-24,2,0,0,2,Americas,NaN
1006,NaN,US,40.0,-100.0,2020-01-25,2,0,0,2,Americas,NaN
1267,NaN,US,40.0,-100.0,2020-01-26,5,0,0,5,Americas,NaN
...,...,...,...,...,...,...,...,...,...,...,...
47986,NaN,US,40.0,-100.0,2020-07-23,4038816,144430,1233269,2661117,Americas,NaN
48247,NaN,US,40.0,-100.0,2020-07-24,4112531,145560,1261624,2705347,Americas,NaN
48508,NaN,US,40.0,-100.0,2020-07-25,4178970,146465,1279414,2753091,Americas,NaN
48769,NaN,US,40.0,-100.0,2020-07-26,4233923,146935,1297863,2789125,Americas,NaN
49030,NaN,US,40.0,-100.0,2020-07-27,4290259,148011,1325804,2816444,Americas,NaN

In [101]:
print(df_csv.loc[df_csv['Confirmed']>1000,['Province/State','Country/Region']].head(10))

     Province/State Country/Region
1105          Hubei          China
1366          Hubei          China
1627          Hubei          China
1888          Hubei          China
2149          Hubei          China
2410          Hubei          China
2671          Hubei          China
2932          Hubei          China
3193          Hubei          China
3454          Hubei          China

In [103]:
data={'player':['Virat','Sachin','Dhoni'],'Runs':
      [107,150,110],'Matches':[42,150,97]}

In [105]:
df1=pd.DataFrame(data)
df1

   player  Runs  Matches
0   Virat   107       42
1  Sachin   150      150
2   Dhoni   110       97

In [109]:
df1.loc[df1['Matches']>50,['player','Matches']]

   player  Matches
1  Sachin      150
2   Dhoni       97

In [111]:
filteredbycountries=df_csv[df_csv['Country/Region'].isin(['US','India','China'])]

In [117]:
filteredbycountries

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region,State
48,Anhui,China,31.825700,117.22640,2020-01-22,1,0,0,1,Western Pacific,Anhui
49,Beijing,China,40.182400,116.41420,2020-01-22,14,0,0,14,Western Pacific,Beijing
50,Chongqing,China,30.057200,107.87400,2020-01-22,6,0,0,6,Western Pacific,Chongqing
51,Fujian,China,26.078900,117.98740,2020-01-22,1,0,0,1,Western Pacific,Fujian
52,Gansu,China,35.751800,104.28610,2020-01-22,0,0,0,0,Western Pacific,Gansu
...,...,...,...,...,...,...,...,...,...,...,...
48885,Xinjiang,China,41.112900,85.24010,2020-07-27,311,3,73,235,Western Pacific,Xinjiang
48886,Yunnan,China,24.974000,101.48700,2020-07-27,190,2,186,2,Western Pacific,Yunnan
48887,Zhejiang,China,29.183200,120.09340,2020-07-27,1270,1,1268,1,Western Pacific,Zhejiang
48936,NaN,India,20.593684,78.96288,2020-07-27,1480073,33408,951166,495499,South-East Asia,NaN
49030,NaN,US,40.000000,-100.00000,2020-07-27,4290259,148011,1325804,2816444,Americas,NaN

In [119]:
filteredbycountries.nunique()

Province/State      33
Country/Region       3
Lat                 35
Long                35
Date               188
Confirmed         1226
Deaths             355
Recovered         1206
Active             855
WHO Region           3
State               33
dtype: int64

In [121]:
df_csv.nunique()

Province/State       78
Country/Region      187
Lat                 260
Long                261
Date                188
Confirmed         10861
Deaths             3640
Recovered          7609
Active             8641
WHO Region            6
State                78
dtype: int64

In [125]:
df_sql = df_csv.query("Confirmed<1 and Deaths <1 and 'Country/Region' =='India'")

In [127]:
df_sql

Empty DataFrame
Columns: [Province/State, Country/Region, Lat, Long, Date, Confirmed, Deaths, Recovered, Active, WHO Region, State]
Index: []

In [129]:
df_sql.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  0 non-null      object
 1   Country/Region  0 non-null      object
 2   Lat             0 non-null      float64
 3   Long            0 non-null      float64
 4   Date            0 non-null      object
 5   Confirmed       0 non-null      int64
 6   Deaths          0 non-null      int64
 7   Recovered       0 non-null      int64
 8   Active          0 non-null      int64
 9   WHO Region      0 non-null      object
 10  State           0 non-null      object
dtypes: float64(2), int64(4), object(5)
memory usage: 0.0+ bytes

In [133]:
data = {'City':['hyderabad','chennai','delhi'],'Matches-played':
        [52,30,25],'wins':[40,28,15]}
df2 = pd.DataFrame(data)

In [135]:
df2

        City  Matches-played  wins
0  hyderabad              52    40
1    chennai              30    28
2      delhi              25    15

In [167]:
filtered_df2 = df2.query('`Matches-played` > 25 and wins > 20')

In [169]:
filtered_df2

        City  Matches-played  wins
0  hyderabad              52    40
1    chennai              30    28

In [179]:
data1 = {'Customers':['Sakshi','Harsh','Saumya'],'Amount':[16000,13000,21000],'city':['Hyderabad','patna','Lucknow']}
df3 = pd.DataFrame(data1)

In [181]:
df3

  Customers  Amount       city
0    Sakshi   16000  Hyderabad
1     Harsh   13000      patna
2    Saumya   21000    Lucknow

### And operator

In [183]:
and_op = df3[(df3['Amount']>15000) & (df3['Amount'] <21000)]
and_op

  Customers  Amount       city
0    Sakshi   16000  Hyderabad

In [187]:
or_op = df3[(df3['Amount'] > 15000) | (df3['Amount'] < 21000)]
or_op

  Customers  Amount       city
0    Sakshi   16000  Hyderabad
1     Harsh   13000      patna
2    Saumya   21000    Lucknow

In [191]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [195]:
df_diamond = sns.load_dataset("diamonds")

In [196]:
df_diamond

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [199]:
df_diamond.size

539400

In [201]:
df_diamond.shape

(53940, 10)

In [205]:
print(df.head)

<bound method NDFrame.head of   country    state     capital
0   India    bihar   New delhi
1     usa  chicago  washington
2      uk  britain      london>

In [207]:
df_diamond.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [209]:
df_diamond['clarity']

0        SI2
1        SI1
2        VS1
3        VS2
4        SI2
        ...
53935    SI1
53936    SI1
53937    SI1
53938    SI2
53939    SI2
Name: clarity, Length: 53940, dtype: category
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

In [211]:
df_diamond.clarity

0        SI2
1        SI1
2        VS1
3        VS2
4        SI2
        ...
53935    SI1
53936    SI1
53937    SI1
53938    SI2
53939    SI2
Name: clarity, Length: 53940, dtype: category
Categories (8, object): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

In [217]:
df_diamond.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [219]:
data ={'Name':['Sakshi','Sadvika','srivalli'],'Age':[16,20,18],'Score':[49,50,50]}

In [223]:
df4= pd.DataFrame(data, index=['Bihar','Amberpet','Ramanthapur'])
df4

                 Name  Age  Score
Bihar          Sakshi   16     49
Amberpet      Sadvika   20     50
Ramanthapur  srivalli   18     50

In [225]:
# sort rows by index
sorted_df = df4.sort_index()
sorted_df

                 Name  Age  Score
Amberpet      Sadvika   20     50
Bihar          Sakshi   16     49
Ramanthapur  srivalli   18     50

In [227]:
#sort column by index
sort_col = df4.sort_index (axis=1)
sort_col

             Age      Name  Score
Bihar         16    Sakshi     49
Amberpet      20   Sadvika     50
Ramanthapur   18  srivalli     50

In [229]:
#sort rows by values
sort_age = df4.sort_values(by='Age')
sort_age

                 Name  Age  Score
Bihar          Sakshi   16     49
Ramanthapur  srivalli   18     50
Amberpet      Sadvika   20     50

In [233]:
sort_age1 = df4.sort_values(by='Score', ascending = False)
sort_age1

                 Name  Age  Score
Amberpet      Sadvika   20     50
Ramanthapur  srivalli   18     50
Bihar          Sakshi   16     49

In [235]:
data = {'Name':['Uma','Ramesh','varun'],'Age':[25,20,35],
        'Score':[25,80,75]}
df5 = pd.DataFrame(data, index=['b','c','a'])
df5

     Name  Age  Score
b     Uma   25     25
c  Ramesh   20     80
a   varun   35     75

In [237]:
# Sorting for multiple columns
sort_multi = df5.sort_values(by=['Age','Score'],ascending=[False,True])
sort_multi

     Name  Age  Score
a   varun   35     75
b     Uma   25     25
c  Ramesh   20     80

In [245]:
data = {'Name':['Aditya','Deepak','Ankit','Sakshi'],'Age':[20,20,20,20],
        'Score':[90,70,80,60]}
index_df6 = ['AI01','AI02','AI03','AI04']
df6 = pd.DataFrame(data, index=index_df6)
df6

        Name  Age  Score
AI01  Aditya   20     90
AI02  Deepak   20     70
AI03   Ankit   20     80
AI04  Sakshi   20     60

In [249]:
arrays=[['Team A', 'Team A' ,'Team B', 'Team B'],['Player 1','Player 2','Player1','Player2']]
index = pd.MultiIndex.from_arrays(arrays,names=('Team','Player'))
index

MultiIndex([('Team A', 'Player 1'),
            ('Team A', 'Player 2'),
            ('Team B',  'Player1'),
            ('Team B',  'Player2')],
           names=['Team', 'Player'])

In [253]:
data = {'Score':[90,105,85,65]}
df_score = pd.DataFrame(data, index=index)
df_score

                 Score
Team   Player
Team A Player 1     90
       Player 2    105
Team B Player1      85
       Player2      65